### PR TITLE
Extract repo ID with regex

### LINKED ISSUE #7: $ gh-description without arguments throws error
What request is this sending? What is does the command `gh-description` without any arguments do?

screen shot 2017-02-05 at 15 38 22

This happens in a public git repo folder.

### PR DESCRIPTION
**Pull request by fregante**
Fixes #7

### CODE REVIEW

**Comment by RichardLitt** [comment]
Breaks for `git@github.com:RichardLitt/gh-description.git`. I found another solution:  `res = res.replace(/\.git/g, '')`. Should work for both. Want to implement that and I'll merge?

**Comment by RichardLitt** [comment]
We should really have tests for all of these.

**Comment by fregante** [comment]
How about this? If it can be done with a single regex and without `if`s, I'd prefer that

**Comment by RichardLitt** [comment]
Works for me!

**Pull request merged**
